### ISSUE TITLE
Prevent changing username/password

### ISSUE THREAD

**Issue by math-GH** [FreshRSS/xExtension-Demo#1]
Someone changed username or password of the demo so that interested users cannot login anymore.

Is it possible to prevent changing username and password?

If not, could we do some simple UI changes like disable the inputs or hide the elements to change username and password?

**Comment by marienfressinaud** [comment]
There's always a way :) It should be fixed: https://github.com/FreshRSS/xExtension-Demo/commit/99c0503282c6ca3daf105ca08be872a00343a47e
